# Site settings
title: Anjul Tyagi
email: aktyagi@cs.stonybrook.edu
description: > # this means to ignore newlines until "baseurl:"
  Anjul Tyagi: PhD student in Computer
  Science & Engineering at Stony Brook University.
  Interested in Visual Analytics and Data Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tyagi-iiitv.github.io/" # the base hostname & protocol for your site
production_url: "https://tyagi-iiitv.github.io/"
github_username: tyagi-iiitv
permalink: /blog/:year/:month/:title.html
disqus: tyagi-iiitv-github-io
twitter:
  username: tyagi_anjul_ds

sass:
  style: compressed

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
